version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'CartoDB/frontend-team'
    groups:
      deck-gl:
        patterns:
          - '@deck.gl/*'
      luma-gl:
        patterns:
          - '@luma.gl/*'
      angular:
        patterns:
          - '@angular/*'
      react:
        patterns:
          - 'react'
          - 'react-*'
          - '@types/react'
          - '@types/react-*'
      vue:
        patterns:
          - 'vue'
          - 'vue-*'
      dev-dependencies:
        dependency-type: 'development'
