name: Template CI

on:
  push:

jobs:
  test-template:
    name: Test template [Node.js ${{ matrix.node-version }} ${{ matrix.framework }}]
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        framework: [react, vue, angular]

    env:
      PROJECT_PATH: projects/node-${{ matrix.node-version }}/${{ matrix.framework }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      ##########################################################################
      # Build
      ##########################################################################

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      ##########################################################################
      # Test template
      ##########################################################################

      - name: Create project for ${{ matrix.framework }} node-${{ matrix.node-version }}
        run: |
          mkdir -p ${PROJECT_PATH}
          yarn create @carto/${{ matrix.framework }} ${PROJECT_PATH}

      - name: Create project for ${{ matrix.framework }} node-${{ matrix.node-version }}
        run: |
          cd ${PROJECT_PATH}
          yarn
          yarn dev
