name: Template CI

on:
  push:

jobs:
  test-template:
    name: Test template [Node.js ${{ matrix.node-version }} - Framework ${{ matrix.framework }}]
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        # If you want to exec in all node versions, uncomment the next line
        #node-version: [18.x, 20.x, 22.x]
        # If you want to exec in a specific framework, uncomment the next line
        #framework: [react, vue, angular]

        # Execution
        node-version: [20.x]
        framework: [react]

    env:
      PROJECT_PATH: projects/node-${{ matrix.node-version }}/${{ matrix.framework }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Corepack
        run: corepack enable

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Create project with framework ${{ matrix.framework }} node-${{ matrix.node-version }}
        env:
          CARTO_AUTH_TOKEN: ${{ secrets.CARTO_AUTH_TOKEN }}
        run: |
          mkdir -p ${PROJECT_PATH}
          node scripts/generate-ci-project.js ${{ matrix.framework }} ${PROJECT_PATH} ${CARTO_AUTH_TOKEN}

      - name: Start project
        run: |
          set -x
          cd ${PROJECT_PATH}
          rm tarn.lock
          yarn
          yarn dev
